web:
  image: mmiglier/web
  ports:
   - "3333:3333"
  links:
   - accounts
   - registration
registration:
  image: mmiglier/registration
  ports:
   - "1111:1111"
accounts:
  image: mmiglier/accounts
  ports:
   - "2222:2222"
  links:
   - registration